#docker compose -f docker-compose.windows.yml up -d
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"   # Interfaz web
      - "1025:1025"   # SMTP

    volumes:
      - mailhog:/data
    restart: always

# En tu app configura:
# SMTP_HOST = localhost
# SMTP_PORT = 1025

volumes:
  mailhog:
