services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ${DOCKER_VOLUME_ABSOLUTE_PATH}/seq-data:/data
    restart: always
