services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Cbmwjmkq23
    volumes:
      - ${DOCKER_VOLUME_ABSOLUTE_PATH}/sql-data:/var/opt/mssql
    restart: always