#Run SQL Server 2022 on Windows using Docker Compose
# This file is used to run SQL Server 2022 on Windows using Docker Compose.
#docker compose -f docker-compose.windows.yml up -d

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - sql1:/var/opt/mssql
    restart: always

volumes:
  sql1: