services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"    # Acceso a la interfaz Web
      - "9443:9443"    # Acceso a la interfaz Web por HTTPS (opcional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    restart: unless-stopped
