global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'gt-trace-packaging-api'
    metrics_path: /gtt/services/packaging/metrics
    static_configs:
      - targets: ['mxsrvapps.gt.local']
        labels:
          instance: 'GT Packaging API'

  - job_name: 'MXSRVDEV'
    metrics_path: /metrics
    static_configs:
      - targets: ['mxsrvdev:9182']
        labels:
          instance: 'MXSRVDEV Server'

  - job_name: 'MXRPP202401 - raspberrypi'
    metrics_path: /metrics
    static_configs:
      - targets: ['172.30.18.15:9100']
        labels:
          instance: 'ESD Raspberrypi'